language: node_js

node_js:
  - "11.3.0"
branches:
  only:
    - dev
install:
  - npm install -g yarn
  - yarn
script:
  - yarn
  - yarn build
env:
 global:
   - GH_REF: github.com/wuhaohao1234/wuhaohao1234.github.io