language: node_js

node_js:
  - "11.3.0"

branches:
  only:
    - dev
env:
  - EMBER_VERSION=default
install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn
script:
  - yarn
  - codecov
  - yarn build

